sudo: required
services:
- docker
env:
  matrix:
  - JENKINS_HOME=true
language: java
jdk:
- openjdk8
branches:
  only:
  - master
before_install:
- echo "MAVEN_OPTS='-Xmx256m'" > ~/.mavenrc
- curl -o $HOME/.m2/settings.xml https://raw.githubusercontent.com/dangernoodle-io/dangernoodle-io-build-pom/master/src/main/travis/settings.xml
install: true
script:
- mvn -B -V verify jacoco:report coveralls:report -DskipITs
notifications:
  email: false
  slack:
    secure: bibkNRbYa7ezQEfon8OIWCyaM5R94DQr9pVRldZdKRkdP5U+67k9oZYbo04KNfV6co/TJmB5ALZAolaGsEwb9pAErv43yWWnunz2KTFWYi7P8xTODVu4B8B0F6FZMp7YB1yHgLrrg1Pkg+mzo8Uk3ruGL2haOTpi4xm1P55b/Tfa3HMx3msymz08DMzBRLQpztjJ8veWDBtt09WZ4b/WKEq2ilfybeympPI6a5ITlYez853fQDUNXTpc/m6SD6WwmsAZRX2BCfH1Icd3KqVZ6p0Gn0/hYurjNqQqBleXeW6zAYttKK8bKDCiUMFrJw6vE6X4I4fRD9Y31+3Hy7PFIipTjSa64S8r9N4Bgqy5xLsX0oPewIKnj30qH8lso6m4zbsgc22OWseuxbna/7Wv2HMtlUEZfvu6XGiQUzP/F8ytDWy2QwboOsER7ZQ9FiLyF3bgrru/3ucT7ofm7nZFvTKTAObeYmUM0q+TzkEWaKWh+aC5W+3aHuAyWMg5aL0A6ydgONO7NsBMlHvnleph/xPkE4lQgWcg25Ow9NmdvNAfkZ6GikMXJ7bSp+RnxFitnYskXIR/EDnnVVv3x2VDwFPLMNFt5gmgE6+ThxRKqJHLsBWpmC5lUJZwB9fZIPKWrutZgxbx1c8iSgpp+ts+kO0jH6cW0BeVXT5OS9kDJVA=
