sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - JENKINS_HOME=true
  - secure: F4uKO8PZ94lMrhWvKU+0NxiXE0CwD+5N3rhoptsj+Dl+4ktrysBr+z8MC40BR/lV1HkaNtnOv2VMDf3xV0v6RzLflC/MALmMDmVzuMEWQcJ52Da73Gz2JcBb8o3UU3Ph1KlKxKHsTPKeo08H0TsCkVh9v9bHGsSeSYXUSV4OSOVZkPJ+IIi/eoFWa77lXzZ7LVASmufgv7XYDOYjZLhPbWYmktiFh8BQQn8hRV5L0Y6r6I82KFalq8nUXUba2EOrfbbZXfiJ5TWP6Lnjz9QABhKFepffX0D173GDjeVlkSXQf14769+npoFV5XrwUDKtPfh4HIC3pvlgVcCSQurl/IlKGisyVFRKTCBg0WYqHMVSn2/ltv5pURJonefnwbox6Atd5fzfleWvyPtPnf/Q4o5VU07gvpj4ejCYu+gWJ2RtSXwIS+NYxkZL5vnT8ZbQMiYqEOnq36fCXhGzYA//BAKocHoIWXs2IclrEnkg+SRgDD6A3+t4BWYKt9tJZioHowdGjbvtQCqDrDM2HlWf92CUNR6aUrRcDzRY12Q48z61V3iYhX7zAy9FWH/5exWP3FcKadsP8eyeFzXGN01+ep6zkc3dyuIADHEoDEO25utui508CsbhdQbrlH3JOqU/+e+2aUO8FtC8mL59X8j7L+PHnp1W/nUycmm60z2p/dg=
language: java
jdk:
- openjdk11
branches:
  only:
  - master
before_install:
- echo "MAVEN_OPTS='-Xmx256m -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'" > ~/.mavenrc
- curl -o $HOME/.m2/settings.xml https://raw.githubusercontent.com/dangernoodle-io/dangernoodle-io-build-pom/master/src/main/travis/settings.xml
install: true
script:
- mvn -B -V verify jacoco:report coveralls:report -DskipITs
notifications:
  email: false
  slack:
    secure: YT9/He/bgwgm8vvUjokvuOfNx2cfk5EYJ49SMNDx7Qi2O/NwH3Rlmf9IwVp+uyTOqAwZn6fNmbc4aclteZ7kj/FzuOExXtVgJIZk+9vtHuogMoiFNLZj+ukV/MRFFhBuD1OrnbMdf3dWx8NYGpsR8IN+tRK7nhxd/+rEd5D3hrQj+gKBYPMLxj5C78LO35BdBKtUwgKu4Y3JMIvsyQftYsGYaq6bt04Pltszyoxq05ZjEvvGW3s6sNKwKcTyfDWPUyrH+mFHOt3kAi6U0vF5lEcIVSlA8E1YCz2JrKPQPgRa59wkQ5bs85BXRF8suXswQlCb9ckKdO/C2My/BMJzPu7mdxUPRRHJ+9b552HFR3+7LflIC3+HiAvl8TmwntDu3rnGLDZnfg7PswtGVTWfo8Mtw8vJazQaN4/bXvBSbEI5J4gjoUdVBcZMyykg+p7Md7Iq5sktBXcI7aD8GrzGTFYkkRwkjFY2dEcq1Jvhx1zo9ExsPkXo2+cNdLxgnga2aCdYnxJVZlcAjR0TG9J+BcY7TIU3yyIFmKkPVUq/Nc3uMjBhBfdZ3MZqZXArY6qbbovjEmMn5YwHNAGGqnD56JCfTZhMDH0U0K6T0IT285iJkZKQizL/wbLyhwJ13zasXC+1wy5Y7UsI1QmVe1q7TgfmS02ixsZFTi71pwIMGHk=
